### ISSUE TITLE
Can we handle n-dimensional arrays with Transducers?

### ISSUE THREAD

**Issue by juliohm** [tkf/Transducers.jl#21]
I am particularly interested in defining training examples for statistical learning tasks. For example, suppose I have a type that is an iterator already, and resembles an "image". That is, it is n-dimensional objects that I can loop as if it was linear assuming a row-major order. Now, I want to define a set of Transducers to take this raw iterable image, and produce at the end a set of tiles. That is, sub-images of given size that can be produced with overlap or with a given stride.

Would Transducers handle this use case? Would it be a smart choice? I am very new to the concept, but it seems quite powerful to manipulate shapes lazily, and then just at the very end, access the data.

**Comment by tkf** [comment]
I don't quite understand the function you need to write.  If you have some examples, it would help.  (My first guess was that it was some kind of minibatched iterations but then you are talking about tiles so it's probably not the case?)

> take this raw iterable image, and produce at the end a set of tiles

Transducers are good at processing things as they come.  So, if the transducer has to wait until the very end to produce any output, it is a bit strange usecase.  This _can_ be done with the [`complete`](https://tkf.github.io/Transducers.jl/dev/interface/#Transducers.complete) protocol.  But it's not the first thing I'd try.

There are transducers that can "chunk" inputs, like [Partition](https://tkf.github.io/Transducers.jl/dev/manual/#Transducers.Partition) and [PartitionBy](https://tkf.github.io/Transducers.jl/dev/manual/#Transducers.PartitionBy).  But I don't recommend using them if you know that there are no pre-processing transducers (e.g., filtering) because they have performance penalties.  In such case, defining foldl (or just a iterator) is much easier and optimizable.  See `circularwindows` example in [AdHocFoldable](https://tkf.github.io/Transducers.jl/dev/manual/#Transducers.AdHocFoldable).

**Comment by juliohm** [comment]
Thank you for the clarification. What I have in mind is a collection of utilities for producing batches of training examples, like tiles with labels when the dataset is an image. From what I understood, Transducers.jl aren't ideal for these scenarios and so I will continue with alternative solution strategies.

Thanks again for the package, really useful!
