### ISSUE TITLE
Inference of `reduce` and `dreduce`

### ISSUE THREAD

**Issue by devmotion** [tkf/Transducers.jl#267]
I started playing around a bit with Transducers (very cool but I'm still a bit confused :smile:) and noticed that the following example from the docs infers correctly
```julia
foldl(+, Map(exp) |> Map(log), 1:3)
```
whereas the compiler (Julia 1.4.1, Transducers 0.4.26) can't infer the return type of
```julia
reduce(+, Map(exp) |> Map(log), 1:3)
```
and
```julia
dreduce(+, Map(exp) |> Map(log), 1:3)
```
Adding `init = 0.0` does not fix the problem (additionally, after reading through the docs I assumed that `+` will be handled nicely by default since `Init(+)` is already defined). Is there anything that I could do as a user to ensure that these two calls are inferred correctly?

**Comment by tkf** [comment]
Threaded reduce currently can't be inferred because of the limitation of how Julia's `Task` work (which may be eliminated in the future https://github.com/JuliaLang/julia/issues/35690). Similar limitation applies to distributed processing.

For now, using threaded tasks and communicating with remote workers are more expensive than a dynamic dispatch.  So, I don't think it matters a lot in practice.  Though it may be a PITA sometimes as you need to introduce a function boundary if you need to do some high-performance computation after using reduce.

In principle, I think it is possible to make the inference work (if it works with `foldl`) but that requires a bit of compiler hackery which is always brittle...

**Comment by devmotion** [comment]
Oh I see, that's a bit unfortunate but I guess then I'll probably introduce a function boundary. Thanks for the explanation!
