### ISSUE TITLE
Possibility to store and restore state

### ISSUE THREAD

**Issue by schlichtanders** [tkf/Transducers.jl#283]
Thanks a lot for this package!

I am trying to use Transducers.jl in a streaming setting, where I need to account for possible failure or intentional shutdown of the system.
For such scenarios it is important to be able to backup the streaming application in some way so that I can later restart it at well-defined points in time.

As certain Transducers.jl support states, is there a way to
* programmatically extract the overall state, and
* initialise a transducers with a given state?

**Comment by tkf** [comment]
I was a bit hesitant to expose the internal/private state as the public API, mainly because that's what Clojure does.  But I spend so much effort to make the implementation "pure" so probably I shouldn't afraid of it.

Anyway, this is possible now, even though I don't advertise too much inside the documentation:

```julia
using Transducers
using Transducers: start, complete

xf = Scan(+)
rf = reducingfunction(xf, push!)

init = []
acc = let acc = start(rf, init)
    # Following `for` loop is usually implemented as `__foldl__`
    for x in 1:3
        acc = rf(acc, x)
    end
    acc
end

result = complete(rf, acc)  # this returns an array
```

The variable `acc` holds the entire state of the transducer `xf` + reducing function `rf`.  You can extract the end result with `complete`.

> * initialise a transducers with a given state?

Do you mean to control the state of each transducer manually?  There is no comprehensive API for this.  It's mainly because the state is an implementation detail for each transducer.  Each transducer has to expose the API to do it (e.g., `Scan` has the `init` argument).

**Comment by schlichtanders** [comment]
Thanks a lot for the comprehensive answer.
That is perfectly what I was looking after!

my question `initialise a transducers with a given state`, is actually obsolete now. Seeing, that I can store the whole `acc`, which includes the states, I can initialise the system again, by just using the previous acc.

I.e. I can now do
```
acc = rf(acc, 4)
result = complete(rf, acc)
```
and continue in this sense from where I stopped before. That is all I was after.

**Comment by schlichtanders** [comment]
Short sidenote question:
What is the reason you are storing the bottom reducing function `push!` in the `acc`?

Isn't it already stored in the reducingfunction `rf`?

**Comment by tkf** [comment]
> I can now do
> 
> ```
> acc = rf(acc, 4)
> result = complete(rf, acc)
> ```
> 
> and continue in this sense from where I stopped before.

Once you call `complete`, the state `acc` may not be valid anymore or consistent when restarted.  This is because `acc` can hold some mutable buffer or something which can be destroyed during `complete`.  Also, some transducers "flush" items during `complete`.  So, if you restart the reduction, you might see some items twice.  You can use `Transducers.unwrap_all(acc)` to peak into the current "bottom" result.  It was not meant to be a public API but maybe there is not much harm.

> What is the reason you are storing the bottom reducing function `push!` in the `acc`?

`acc` actually doesn't store the value of `push!`. It only includes the type of the corresponding (composite) reducing function in the type parameter. This is because it can be used to auto-derive `complete` function based on the type. It's not used anymore, though, so that the type parameters can be simpler (and perhaps more compiler-friendly).

**Comment by schlichtanders** [comment]
thanks for the warning and the extra details

for streaming applications, the application practically never ends. Hence transducers which rely on `complete` are not very apt from the very beginning for such streaming applications.
I would just focus on the subclass of transducers which can be stopped and resumed easily

**Comment by tkf** [comment]
Ah, interesting. That makes sense.

**Comment by tkf** [comment]
Actually, I think there are still some dangers. See:

```julia
julia> xf = PartitionBy(x -> x ÷ 3) |> Map(copy);

julia> rf = reducingfunction(xf, push!);

julia> acc = start(rf, []);

julia> for x in 1:7
           acc = rf(acc, x)
       end

julia> complete(rf, acc)
3-element Array{Any,1}:
 [1, 2]
 [3, 4, 5]
 [6, 7]

julia> for x in 8:12
           acc = rf(acc, x)
       end

julia> complete(rf, acc)
6-element Array{Any,1}:
 [1, 2]
 [3, 4, 5]
 [6, 7]
 [6, 7, 8]
 [9, 10, 11]
 [12]
```

As you can see, `6, 7` are duplicated.

**Comment by schlichtanders** [comment]
surprising...

implicitly you seem to say, that this is intended behaviour, is it?
or can this be easily adapted to support save stop/continue semantics?

**Comment by tkf** [comment]
Well, it's not intended but expected, since transducers in Transducers.jl are not meant to be restarted after `complete`.

I think `Transducers.unwrap_all` is what you need:

```julia
julia> for x in 1:7
           acc = rf(acc, x)
       end

julia> unwrap_all(acc)
2-element Array{Any,1}:
 [1, 2]
 [3, 4, 5]

julia> for x in 8:12
           acc = rf(acc, x)
       end

julia> unwrap_all(acc)
4-element Array{Any,1}:
 [1, 2]
 [3, 4, 5]
 [6, 7, 8]
 [9, 10, 11]
```

**Comment by schlichtanders** [comment]
Thanks a lot! Indeed this looks like the final bit for my usecase.

Thank you very much for all the support!
