### ISSUE TITLE
Iterators.product equivalent

### ISSUE THREAD

**Issue by milesfrain** [tkf/Transducers.jl#49]
Is there something similar to [Iterators.product](https://docs.julialang.org/en/v1/base/iterators/index.html#Base.Iterators.product) that can be used with transducers? Or does that not work well with the push (rather than pull) design?

A vague use case involves:
* Take an input stream and generate a group of transducers from each input.
* For each transducer group, lazily generate every combination of these transducer outputs. This means that each transducer will need to be restarted n times (where n is the product of the number of outputs of the other transducers).
* Use another transducer to receive each combination of these outputs and perform additional processing.

Here's a made-up example of this workflow with iterators / generators:
``` jl
generator_group(i) = (10+a:12+a for a in i:i+2)

product_of_group(i) = Iterators.product(generator_group(i)...)

products_of_all_inputs(input_stream) = (product_of_group(i) for i in input_stream)

reduce_products(p) = prod(log10(sum(a)) for a in p)

output_stream(input_stream) = (reduce_products(p) for p in products_of_all_inputs(input_stream))

julia> collect(output_stream(4:10))
7-element Array{Float64,1}:
 1.231272857363814e6 
 1.8740498531431444e6
 2.768192561968704e6 
 3.983011512381036e6 
 5.59969239914248e6  
 7.712141985522048e6 
 1.0427790888162771e7
```

**Comment by tkf** [comment]
Short answer: Use `Iterators.product(...)` as an input of `foldl` etc. Transducers.jl already has specialized method to handle it.

The easiest way to do this is to just put `eduction` like this

```julia
reduce_products(p) = prod(eduction(log10(sum(a)) for a in p))
```

which is equivalent to

```julia
reduce_products(p) = foldl(*, Map(log10 ∘ sum), p)  # maybe pass `simd=true`
```

Longer answer: Transducers are about processing inputs one by one.  So, it's not a good construct for modeling `product` which requires you to go back to the beginning of each sub-collections multiple times.  (Unless you want to cache all history which is not very memory-efficient)  The best way to do it is to do this is where you do the loop; i.e. inside `foldl`.  We need a lazy collection to bundle all the sub-collections together so that `foldl` can be dispatched on the type.  However, `Iterators.Product` returned from `Iterators.product` is a perfect type for this purpose.
