### ISSUE TITLE
Alternative to `collect` to obtain array-like result ?

### ISSUE THREAD

**Issue by atthom** [tkf/Transducers.jl#54]
I am still learning how to properly use Transducers and I've seen the unusual efficacity of `mapfoldl `and `foldl` for mapping and reducing a "reductible".
However, I still struggle to understand how I avoid reducing my iterable as I want a list as a result.
Is `collect` the fast and appropriate way to use a chain of Map / Filter in this case? If not what should I use and how?
So far my code seems like this:
`result = collect(long_process_chain, lazy_iterable)`

**Comment by tkf** [comment]
> So far my code seems like this:
> `result = collect(long_process_chain, lazy_iterable)`

This looks fine to me.  Do you mean that you want `result` to be a collection other than a `Vector` (like some other custom array type)?

Note that `collect` is more or less equivalent to `foldl(push!, input_collection, init=Union{}[])`.  So, if you have a data structure you want to use as a destination, you can pass it instead of `Union{}[]`, if it supports `push!`.

**Comment by atthom** [comment]
I was thinking that `collect` wasn't the best function in this case. As `mapreduce` has a more performant equivalent (`mapfoldl`) with transducers: 

![image](https://user-images.githubusercontent.com/14034413/66168370-744b5b80-e63d-11e9-8e8f-bb46047f27f6.png)

And thanks to your advice I now understand how to populate my list. However, the performance on this case is at the advantage of the collect:

![image](https://user-images.githubusercontent.com/14034413/66168955-0a33b600-e63f-11e9-9a6c-e87223da3e94.png)

![image](https://user-images.githubusercontent.com/14034413/66168984-23d4fd80-e63f-11e9-9bba-f67eaa546380.png)

**Comment by tkf** [comment]
Oops, sorry, I meant `push!!` from BangBang.jl, not `push!`.  I think the performance difference between `mapfoldl` and `colelct` you are seeing is due to the boxed type elements in `Vector{Any}` vs concrete type elements in `Vector{Int}`.

If you use `init=Int[]` with `push!`, it could be even better than `collect` (at least for short output).

**Comment by atthom** [comment]
I suppose this is something similar to this?
![image](https://user-images.githubusercontent.com/14034413/66171167-7d412a80-e647-11e9-9413-ea938cc2d97c.png)

The Documentation of [OnInit](https://tkf.github.io/Transducers.jl/dev/manual/#Transducers.OnInit) has been very helpful to understand what I was doing, I think it deserve to be highlighted!

Also what is the difference between `Union{}[]` and `Int[]` ?

**Comment by tkf** [comment]
Yes, the way you call `foldl` is correct.  To see the difference between `push!` and `push!!`, observe that:

```julia
julia> push!(Int[0], 0.5)
ERROR: InexactError: Int64(0.5)
Stacktrace:
 [1] Int64 at ./float.jl:709 [inlined]
 [2] convert at ./number.jl:7 [inlined]
 [3] push!(::Array{Int64,1}, ::Float64) at ./array.jl:866
 [4] top-level scope at REPL[8]:1

julia> push!!(Int[0], 0.5)
2-element Array{Float64,1}:
 0.0
 0.5
```

That is to say, `push!!` would automatically "widen" the collection so that you can push things always.  Note that this means that you need to be extra careful when using it (hence double `!`)

```julia
julia> y = Int[0];

julia> push!!(y, 0.5)
2-element Array{Float64,1}:
 0.0
 0.5

julia> y  # not updated
1-element Array{Int64,1}:
 0
```

However, `push!!` is safe to use as a reducing function (the first argument to `foldl`) because `foldl` always use the returned value.

Now the reason why to use `Union{}[]` is that `Union{}` is the "bottom" type; it's the narrowest of all type.  So, it's the best starting point because you always have the equality

```julia
push!!(Union{}[], x::T) == T[x]  # where T = typeof(x)
```

See also:
<https://tkf.github.io/BangBang.jl/dev/#BangBang.push!!-Tuple{Any,Any,Any,Vararg{Any,N}%20where%20N}>

**Comment by tkf** [comment]
I guess the original question is answered now?
